### ISSUE TITLE
Code Collab

### ISSUE THREAD

**Issue by vinylrichie** [Boulder-Investment-Technologies/lppls#113]
Really excited to try this out, but code collab demo is having the following issue and not sure what to do: 

[*********************100%***********************]  1 of 1 completed
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-14-811d8faff990>](https://localhost:8080/#) in <cell line: 15>()
     13 
     14 # Create observations array (expected format for LPPLS observations)
---> 15 observations = np.array([time, price])
     16 
     17 # Set the max number for searches to perform before giving-up

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 1849) + inhomogeneous part.

**Comment by Joshwani** [comment]
Hi sorry for confusion. This should be fixed in the google colab notebook. The types or shapes of time and price were mismatched for some reason.
