### ISSUE TITLE
Filtering conditions for bubble indicators.

### ISSUE THREAD

**Issue by tucaman** [Boulder-Investment-Technologies/lppls#12]
Playing with the S&P 500 time series for the past recent month, trying to compute the bubble confidence indicator. I noted that neither a bubble early warning nor a bubble end flag would be raised, when running _func_compute_indicator with window_size=125 and smallest_window_size=20.

The filtering conditions in _func_compute_indicator appear too strict. In particular the condition 

`n_oscillation = ((w / 2) * np.log(abs((tc - first) / (last - first)))) > 2.5`

almost never evaluates to true. 

 **I wonder whether you did a similar analysis and noticed the same?** 

I am aware that these are the conditions cited in all reference papers. from Sornette et. al.; However,  I found much more reasonable results  when using the filtering conditions for the confidence indicator as implemented in the R bubble package by Dean Fantazzini [(https://github.com/deanfantazzini/bubble/blob/master/R/LPPL_confidence.R),](url) which is:

`n_oscillation = w /( 2 * math.pi) * np.log(abs(tc / (tc - last))) > 2.5`

Using this much less strict condition, I end up with the indicator values plotted in the attached file:

![SP500_Confidence_Indicator_20200215_20200605](https://user-images.githubusercontent.com/59477617/83954155-ec11fb80-a846-11ea-8847-b2b85c800516.png)

**Comment by Joshwani** [comment]
Hi @tucaman,

Thanks for bringing this up. It appears that I am calculating the number of oscillations incorrectly. I haven't quite wrapped my head around the math but by visualizing a fit and its estimated parameters, it becomes clear that the number of oscillations identified by my current code is much less than what is represented in the plot. For example here is a single fit with many observations.
![download](https://user-images.githubusercontent.com/6832457/84068821-c7bd3880-a986-11ea-84e5-2d581a745cbf.png)
Here are the estimated parameters:
- `tc`: 1411.2478663672039
- `m`: 0.48440456637744556
- `w`: 9.947939150512653
- `a`: 5.054135495639681
- `b`: -0.1199213964144249
- `c`: 0.017175517611846273

And here are the computed number of oscillations via the old and new ways.

- `old n osc`: 0.022069611539656146
- `new n osc`: 8.58127269784443

where 

- `first`: 0
- `last`: 1405

A manual count of the observations in the plot yields ~ 8 so I would like to merge in your proposed change.

Would you like to create a branch and I can review and merge? No worries if not, I can implement it later this week. 

Best,

Josh

**Comment by tucaman** [comment]
Thanks for getting back. I will prepare the change tonight.
