### ISSUE TITLE
minimize failed

### ISSUE THREAD

**Issue by scitao** [Boulder-Investment-Technologies/lppls#22]
lppls.py:57: RuntimeWarning: invalid value encountered in log
  phase = np.log(deltaT) if self.use_ln else deltaT
lppls.py:58: RuntimeWarning: invalid value encountered in power
  fi = np.power(deltaT, m)

minimize failed: SVD did not converge in Linear Least Squares
minimize failed: SVD did not converge in Linear Least Squares
minimize failed: SVD did not converge in Linear Least Squares

**Comment by Joshwani** [comment]
Hi Scitao, I haven't looked into this yet, but do you have nans in your observation data?

**Comment by nightvision04** [comment]
@scitao Can you print our the values of deltaT, m?

**Comment by Joshwani** [comment]
I think I'm going to remove the use_ln attribute and just leave it up to the user if they want to take the log of their data before passing it to the model. Should eliminate the issue where you take the log of a negative number here.

**Comment by QuentinDan** [comment]
@Joshwani @nightvision04 
deltaT:

[1034.83703536 1033.83703536 1032.83703536 ... -220.16296464 -221.16296464
 -222.16296464]

**Comment by QuentinDan** [comment]
this could happen 3 in 10 times of test with sp500.csv

**Comment by Joshwani** [comment]
Just a note - this happens when tc ∈ [t1, t2], which can be a very important case. A way to account for such a case is to take `dT = np.abs(tc - T)`.
