### ISSUE TITLE
Run tests on 'push' instead of 'master'

### ISSUE THREAD

**Issue by nightvision04** [Boulder-Investment-Technologies/lppls#29]
Could we run tests on 'push' instead of master? That would allow forks to be checked against the CI build.

In my latest pull request, I see that the tests failed because my tests for failed convergence raised a ValueError (instead of a numpy.linalg.LinAlgError) in ubuntu-latest.

Since I'm using windows, it's tricky to anticipate some of those platform differences without additionally testing on the CI build.

**Comment by Joshwani** [comment]
Yes, that is fine with me. https://github.com/Boulder-Investment-Technologies/lppls/pull/30
