### ISSUE TITLE
Branchless Programming

### ISSUE THREAD

**Issue by nightvision04** [Boulder-Investment-Technologies/lppls#33]
I think I could squeeze some speed in by applying branchless programming.  Particularly in the indicator function. Is our primary objective speed? It would come at the cost of some readability.

**Comment by Joshwani** [comment]
@nightvision04, if it makes it faster, I'm all about it! Just a note - I'm thinking about merging in the [numba branch](https://github.com/Boulder-Investment-Technologies/lppls/pull/32) soon. Maybe branch from that branch or just keep that in mind if you start adding the branchless stuff. 

I wasn't familiar with branchless programming. Very neat.

**Comment by nightvision04** [comment]
Okay sounds good. I'll do some timing functions to make sure the tradeoff between speed and readability is actually worth it ;)

**Comment by nightvision04** [comment]
I don't think that any of the speed bottlenecks can be significantly addressed by branchless approaches. Closing.
