### ISSUE TITLE
Filtering Condition

### ISSUE THREAD

**Issue by mreismendes** [Boulder-Investment-Technologies/lppls#35]
I'm trying to apply the same conditions of this article:

Demirer, Riza & Demos, Guilherme & Gupta, Rangan & Sornette, Didier. (2017). On the Predictability of Stock Market Bubbles: Evidence from LPPLS Confidence TM Multi-scale Indicators. SSRN Electronic Journal. 10.2139/ssrn.3076609. 

![image](https://user-images.githubusercontent.com/32521301/101780728-a4aa4780-3ad5-11eb-8532-69fb14ab104b.png)

```
filter_conditions_config = [
  {'condition_1':[
      (-0.05, 0.1), # tc_range
      (0.01,1.2), # m_range
      (6,13), # w_range
      2.5, # O_min
      0.8, # D_min
  ]},
  {'condition_2':[
      (-0.05, 0.1), # tc_range
      (0.01,0.99), # m_range
      (6,13), # w_range
      2.5, # O_min
      1.0, # D_min
  ]}
]
```

Am I setting the conditions correctly?

I would appreciate any help. Thank you!

**Comment by Joshwani** [comment]
@mreismendes - the `tc_range` is passed to the [`_get_tc_bounds`](https://github.com/Boulder-Investment-Technologies/lppls/blob/05764bb682307b7bf41db3be5f57b8a477eee6bd/lppls/lppls.py#L300) method and it subtracts the lower and upper from whatever t2 you're working with, so the lower pct bound shouldn't be negative. For example, say you have t2=100, t1=0, lower_pct_bound=-.5 the lower end of the tc range would be 100-(100*-.5) = 150. Really what you want is 100-(100*.5) = 50.

It would probably be more intuitive to have it accept negatives for the lower param.  I can open up a pr for that unless you want to.

Also, you may want to fork the repo and change the search space to be (0.0, 0.2) [here](https://github.com/Boulder-Investment-Technologies/lppls/blob/05764bb682307b7bf41db3be5f57b8a477eee6bd/lppls/lppls.py#L78)

Other than those two items, your config looks good!

The paper you reference is an interesting one. I don't believe the filter conditions in the table are the ones actually used in the calibration process. You may have noticed that the authors don't explicitly mention which filter condition from the table they use to compute the confidence values in Figure 1. In previous literature, using two filter conditions implies that the researcher is computing two sets of indicators for the same time-series: a bubble early warning indicator and a bubble end flag indicator. You can see these in use on the [FCO cockpit](http://tasmania.ethz.ch/pubfco/fco.html). Check the indicators dropdown menu in the upper left.

**Comment by mreismendes** [comment]
@Joshwani Thank you for replying

 I didn't understandd how to set up the "tc bounds". To meet the paper criteria after changing the search space. 

Should I use the below conditions? Is it just tweaking the negative to positive?

```
filter_conditions_config = [
  {'condition_1':[
      (0.05, 0.1), # tc_range
      (0.01,1.2), # m_range
      (6,13), # w_range
      2.5, # O_min
      0.8, # D_min
  ]},
  {'condition_2':[
      (0.05, 0.1), # tc_range
      (0.01,0.99), # m_range
      (6,13), # w_range
      2.5, # O_min
      1.0, # D_min
  ]}
]

```

On page 5 of the paper, there is a reference to the table. But yes, they didn't say which one they used. I'll try to use both and see the results.

![image](https://user-images.githubusercontent.com/32521301/101819434-01bcf200-3b04-11eb-9a78-235b1116627f.png)

Thank you!

**Comment by Joshwani** [comment]
@mreismendes - yes those configs look good.
