### ISSUE TITLE
Data_loader is undefined

### ISSUE THREAD

**Issue by ErickDelgado** [Boulder-Investment-Technologies/lppls#47]
Hey there, I'm trying to run this code but with a btc data set, however, just running it out of the box I am faced with the error that data loader variable is not defined.

**Comment by Joshwani** [comment]
Hi @ErickDelgado, are you able to share the code snippet you're trying to run and the error message? I've been meaning to setup an issues template but haven't got around to it. 

`data_loader` is meant to load an S&P 500 dataset, so it shouldn't be necessary if you're using your own data. Maybe I have a typo in the readme example or maybe something weird is going on with how you're importing the package modules.

**Comment by ErickDelgado** [comment]
Well, I cloned the repo down and ran it as is, I suppose thats the issue. Ultimately I wanted to pump a csv of btc data through this method you've defined here. I'm also a novice with python, is there some init function I should invoke after I've cloned and downloaded the requisite packages? Appreciate your time, thanks.

**Comment by ErickDelgado** [comment]
Trying to run your boilerplate code up until the first visualization gets printed, but it is erroring there. Here are some snippets of code and the error stack trace.

![image](https://user-images.githubusercontent.com/25911292/115063737-f581e080-9eb9-11eb-9b76-b01a41581ae7.png)
![image](https://user-images.githubusercontent.com/25911292/115063761-003c7580-9eba-11eb-8457-b670753309f6.png)
![image](https://user-images.githubusercontent.com/25911292/115063772-0599c000-9eba-11eb-96aa-984d12cf0f25.png)

**Comment by ErickDelgado** [comment]
Hey I figured out all my issues and managed to run your model through with a bitcoin dataset. Thanks for your time.
