### ISSUE TITLE
Name Error

### ISSUE THREAD

**Issue by mferns11** [Boulder-Investment-Technologies/lppls#48]
19 filter_conditions_config=filter_conditions_config
20 )
---> 21 res_df = res_to_df(res, 'condition_1')
22 lppls_model.plot_confidence_indicators(res_df, title='Short Term Indicator 120-30')
23

NameError: name 'res_to_df' is not defined

**Comment by mreismendes** [comment]
I had the same problem.

**Comment by mferns11** [comment]
Any Solutions

**Comment by mferns11** [comment]
res_df = lppls_model.res_to_df(res, 'condition_1')
