### ISSUE TITLE
Minor issue running the example ...

### ISSUE THREAD

**Issue by terminsen** [Boulder-Investment-Technologies/lppls#50]
Hi -

Thanks for posting ! 

Running your example I ran into trouble when you call the function 

res_df = res_to_df(res, 'condition_1')

... as the function res_to_df is not recognized, rather res_df = lppls_model.res_to_df(res, 'condition_1') seems to work fine. 

Thanks, Jesper.

**Comment by Joshwani** [comment]
Thanks Jesper - @StephenYPan has posted a PR to update this issue in the README along with another improvement. I will merge sometime this week.
