### ISSUE TITLE
was using lppl to rolling predict the critical time but got lots of 'SVD did not converge' errors

### ISSUE THREAD

**Issue by plok1221** [Boulder-Investment-Technologies/lppls#9]
tested=pd.DataFrame()
count=0
for i in data[data.trade_date>'20070801'].trade_date.values:
    test_data=data[data.trade_date<=i]
    time = np.linspace(0, len(test_data)-1, len(test_data))
    # create list of observation data, in this case, 
    # daily adjusted close prices of the S&P 500
    price = [p for p in test_data['close']]
    # create Mx2 matrix (expected format for LPPLS observations)
    observations = np.array([time, price])
    
    # the literature suggests 25
    MAX_SEARCHES = 10000

    # instantiate a new LPPLS model with the S&P 500 dataset
    lppls_model = lppls.LPPLS(use_ln=True, observations=observations)

    # fit the model to the data and get back the params
    tc, m, w, a, b, c = lppls_model.fit(observations, MAX_SEARCHES, minimizer='Nelder-Mead')

    # visualize the fit
    #lppls_model.plot_fit(observations, tc, m, w)
    count+=1
    print('calculating {}th data in {}datas'.format(count,len(data[data.trade_date>'20070801'].trade_date.values)))
    tested=tested.append(pd.DataFrame({'date':i,'critical_time':tc,'critical_time2':tc-len(time),'m':m,'w':w,'a':a,'b':b,'c':c},index=[i]))

![image](https://user-images.githubusercontent.com/18573584/82730371-94956b00-9d31-11ea-86f0-b52a54736c5c.png)

**Comment by Joshwani** [comment]
Hi @plok1221, thanks for bringing this up. This can happen when there are inf or nan values in the data. With that said, I will look into adding some data cleansing and maybe throw an error to halt the program if this error comes up.
